#!/bin/bash

sudo apt-get update
sudo apt-get install python
sudo apt-get install python-pip
sudo curl -O https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
sudo apt-get install unzip
sudo mkdir /bin/terraform
sudo unzip terrafrom_0.12.6_linux_amd64.zip -d
export PATH=$PATH:/bin/terraform
terraform --version
